/* *********************
 아래 DDL은 H2 Database를 기준으로 생성되었습니다.
 MySQL 계열 혹은 Oracle DB에서 사용 시 다를수 있으므로 주의해주세요.
 *********************
DROP TABLE IF EXISTS TB_BOARD CASCADE;
CREATE TABLE TB_BOARD
(
    IDX        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    CONTENTS   VARCHAR(255),
    CREATED_AT TIMESTAMP,
    CREATED_BY VARCHAR(255),
    TITLE      VARCHAR(255),
    PRIMARY KEY (IDX)
);
 */
